### ISSUE TITLE
Additional sources and one suggested edit

### ISSUE THREAD

**Issue by maniwani** [MFatihMAR/Awesome-Game-Networking#53]
Thanks for compiling all these resources. This repo has been a huge help to me. I found a few more that I saw weren't listed.

- [2017 / Replay Technology in Overwatch: Kill Cam, Gameplay, and Highlights][1] - Talk by Philip Orwig from Blizzard.

- [2017 / Networking Scripted Weapons and Abilities in Overwatch][2] - Talk by Dan Reed from Blizzard.

- [Rollback Networking in INVERSUS][3] - Blog post by Ryan Juckett.

Last add is that Exit Games (Photon Engine) is releasing a new library called [Fusion][5] (currently in public beta) that will replace Photon Unity Networking (PUN) and Bolt. Those libraries will only receive maintenance updates in the future. Its documentation is a good resource for architecting a networked game.

I also want to suggest revising this description.

- [2017 / Overwatch Gameplay Architecture and Netcode]() - Determinism, responsiveness and precision.

The talk is a broad look at how Overwatch multiplayer works and how ECS helped them make it, so I recommend changing the description to something like:

- [2017 / Overwatch Gameplay Architecture and Netcode]() - Designing a precise, responsive networked simulation and leveraging ECS to reduce complexity by Tim Ford from Blizzard.

I know "determinism" is in the GDC description, but in the context of this repo I think saying it is misleading. Overwatch does not have/use determinism in the same sense that fighting games do. 

Tim Ford was just saying that clients won't rapidly diverge or mispredict because of floating-point tolerances, since Overwatch quantizes floats to a low precision. If a client mispredicts, it was probably because another player did something or excessive packet loss. In the same conference,  Philip Orwig said that Overwatch [is not strictly deterministic][4].

[1]: https://youtu.be/W4oZq4tn57w
[2]: https://youtu.be/ScyZjcjTlA4
[3]: http://blog.hypersect.com/rollback-networking-in-inversus/
[4]: https://youtu.be/W4oZq4tn57w?t=586
[5]: https://doc.photonengine.com/en-us/fusion/current/getting-started/fusion-intro

**Comment by 0xFA11** [comment]
hey @maniwani  — this is an excellent contribution, thank you very much!
when I find some free time, I will add these new items and update existing ones regarding your suggestions.
it's also nice to hear that the list has been helpful to you :)

**Comment by 0xFA11** [comment]
Just a quick update, I'm still onto this. I'm just super busy (or lazy :P) getting back to this.
I will try to find some time soon to update the list with these suggestions, thanks again!

**Comment by 0xFA11** [comment]
done: d8d44dd, 08ccfea, 6095711, 60e4d14
